# Generated by Django 4.2.5 on 2023-09-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('guest', 'Guest')], default='guest', max_length=10),
        ),
    ]
