# Generated by Django 4.1.7 on 2023-09-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_reservationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
